### ISSUE TITLE
167. 两数之和 II - 输入有序数组.js 方法3 遍历有问题

### ISSUE THREAD

**Issue by edward-cq** [DangoSky/algorithm#2]
twoSum([54,21,56,88,33,556,221,22,55,66], 121)
期望结果：[4,5];
实际结果:undefined;

**Comment by DangoSky** [comment]
@chouqing15 题目规定了输入的数组是升序的，而 [54,21,56,88,33,556,221,22,55,66] 不是升序的，所以得到了undefined
